### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by hsuan1117**
Add API of comments

### CODE REVIEW

**Comment by SiriusKoan** [comment]
Can you explain more details?
I don't make sense...

**Comment by hsuan1117** [comment]
Make an API 
So that you can call it in front-end
Maybe use AJAX for loading comments is better

**Comment by SiriusKoan** [comment]
OK, but what's the difference between this and the old post display system?

**Comment by hsuan1117** [comment]
Maybe we don't need API now😛

**Pull request closed without merging**
